### Word Embedding Techniques using Embedding Layer in Keras

In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [5]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [7]:
### Vocabulary size
voc_size=1000

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[753, 313, 947, 265, 855, 374], [341, 516, 947, 532, 807, 366], [623, 487, 215, 774], [753, 630, 947, 913, 753, 856], [760, 574, 225, 947, 532, 807, 366], [586, 947, 532, 807, 483, 420]]


### Word Embedding Represntation

In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [20]:
import numpy as np

In [12]:
## pre padding
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 753 313 947 265 855 374]
 [  0   0   0   0 341 516 947 532 807 366]
 [  0   0   0   0   0   0 623 487 215 774]
 [  0   0   0   0 753 630 947 913 753 856]
 [  0   0   0 760 574 225 947 532 807 366]
 [  0   0   0   0 586 947 532 807 483 420]]


In [13]:
## 10 feature dimesnions
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 10)            10000     
                                                                 
Total params: 10000 (39.06 KB)
Trainable params: 10000 (39.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
embedded_docs[0]

array([  0,   0,   0,   0, 753, 313, 947, 265, 855, 374], dtype=int32)

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 118ms/step


array([[-0.01826002, -0.04246541,  0.00647148,  0.00663867, -0.02410328,
         0.02029507, -0.04503597, -0.00561021,  0.01515058,  0.02196251],
       [-0.01826002, -0.04246541,  0.00647148,  0.00663867, -0.02410328,
         0.02029507, -0.04503597, -0.00561021,  0.01515058,  0.02196251],
       [-0.01826002, -0.04246541,  0.00647148,  0.00663867, -0.02410328,
         0.02029507, -0.04503597, -0.00561021,  0.01515058,  0.02196251],
       [-0.01826002, -0.04246541,  0.00647148,  0.00663867, -0.02410328,
         0.02029507, -0.04503597, -0.00561021,  0.01515058,  0.02196251],
       [ 0.03655586,  0.04217744, -0.03829676, -0.0334556 ,  0.01648642,
         0.02975303, -0.00937439, -0.01658092,  0.03036075,  0.04271488],
       [ 0.04308421,  0.01765312,  0.0311466 , -0.01707548, -0.02066983,
         0.00551951,  0.04691708, -0.04023132,  0.03471709,  0.04360249],
       [ 0.01913929,  0.04518478, -0.03249498,  0.0276394 ,  0.02270149,
         0.02775595,  0.0343966 , -0.00287608

In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 39ms/step
[[[-1.82600245e-02 -4.24654149e-02  6.47147745e-03  6.63866848e-03
   -2.41032839e-02  2.02950723e-02 -4.50359695e-02 -5.61020523e-03
    1.51505806e-02  2.19625123e-02]
  [-1.82600245e-02 -4.24654149e-02  6.47147745e-03  6.63866848e-03
   -2.41032839e-02  2.02950723e-02 -4.50359695e-02 -5.61020523e-03
    1.51505806e-02  2.19625123e-02]
  [-1.82600245e-02 -4.24654149e-02  6.47147745e-03  6.63866848e-03
   -2.41032839e-02  2.02950723e-02 -4.50359695e-02 -5.61020523e-03
    1.51505806e-02  2.19625123e-02]
  [-1.82600245e-02 -4.24654149e-02  6.47147745e-03  6.63866848e-03
   -2.41032839e-02  2.02950723e-02 -4.50359695e-02 -5.61020523e-03
    1.51505806e-02  2.19625123e-02]
  [ 3.65558602e-02  4.21774425e-02 -3.82967591e-02 -3.34555991e-02
    1.64864175e-02  2.97530331e-02 -9.37439129e-03 -1.65809169e-02
    3.03607471e-02  4.27148826e-02]
  [ 4.30842079e-02  1.76531188e-02  3.11465971e-02 -1.70754790e-02
   -2.06698310e-02  5.51950932e

In [ ]:
embedded_docs[0]

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]