## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
# Import libraries
import pandas as pd

In [4]:
df=pd.read_csv('train.csv')

In [5]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
df.shape

(20800, 5)

In [7]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [8]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [9]:
###Drop Nan Values
df=df.dropna()


In [11]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [12]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [13]:
## Get the Dependent features
y=df['label']

In [14]:
X.shape

(18285, 4)

In [15]:
y.shape

(18285,)

In [16]:
#tenserflow implementation
import tensorflow as tf

In [17]:
print(tf.__version__)

2.15.0


In [18]:
#import libraries
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [20]:
### Vocabulary size
voc_size=6000

### Onehot Representation

In [21]:
news=X.copy()

In [23]:
news['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [24]:
news

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [30]:
news.reset_index(inplace=True)  ##code to have index in dataframe because of drop on NaN it may cause index disruption

In [31]:
news

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [32]:
#text nlp
import nltk
import re
from nltk.corpus import stopwords

In [33]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [34]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(news)):
    review = re.sub('[^a-zA-Z]', ' ', news['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [35]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [36]:
corpus[0]

'hous dem aid even see comey letter jason chaffetz tweet'

In [37]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[4765, 5577, 2201, 3436, 1588, 4692, 4988, 3546, 5645, 2122],
 [3779, 2353, 937, 1345, 787, 5336, 2210],
 [5900, 3276, 5600, 959],
 [5339, 3467, 1106, 4110, 3595, 864],
 [2648, 787, 5673, 5418, 925, 316, 787, 847, 2955, 3135],
 [4573,
  5738,
  4810,
  4339,
  75,
  5866,
  261,
  3521,
  2965,
  1590,
  4655,
  2935,
  732,
  3887,
  2210],
 [2315, 4160, 221, 1753, 5364, 4584, 2216, 3406, 1070, 3629, 1069],
 [551, 3525, 2956, 4034, 2258, 1224, 5866, 2112, 1070, 3629, 1069],
 [2252, 4794, 2426, 1829, 2623, 593, 4187, 4875, 5866, 2330],
 [1634, 3398, 4334, 1528, 2909, 1982, 3929, 2659],
 [2038, 987, 4454, 2235, 576, 5342, 5605, 1227, 3581, 2972, 3015],
 [4110, 2251, 1588, 593, 5866, 2258],
 [1872, 3617, 3979, 2978, 4022, 5063, 987, 1820, 5204],
 [1514, 4500, 3095, 2744, 1656, 1523, 2675, 1070, 3629, 1069],
 [92, 229, 3786, 1825, 4749, 1070, 3629, 1069],
 [5138, 71, 4981, 181, 25, 966, 5779, 4785, 870, 2543],
 [3839, 3279, 2353],
 [350, 4868, 3371, 2225, 5866, 1431, 5577, 2210],
 [5812,

In [38]:
corpus[0]

'hous dem aid even see comey letter jason chaffetz tweet'

In [39]:
onehot_repr[0]

[4765, 5577, 2201, 3436, 1588, 4692, 4988, 3546, 5645, 2122]

### Embedding Representation

In [41]:
sent_length=25
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3546 5645 2122]
 [   0    0    0 ...  787 5336 2210]
 [   0    0    0 ... 3276 5600  959]
 ...
 [   0    0    0 ... 1070 3629 1069]
 [   0    0    0 ... 4226 5456 1037]
 [   0    0    0 ... 2826 5448 3855]]


In [42]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0, 3779, 2353,  937, 1345,
        787, 5336, 2210], dtype=int32)

In [43]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 40)            240000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 296501 (1.13 MB)
Trainable params: 296501 (1.13 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [44]:
len(embedded_docs),y.shape

(18285, (18285,))

In [45]:
#convert data into array
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [46]:
X_final.shape,y_final.shape

((18285, 25), (18285,))

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [48]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 19s 81ms/step - loss: 0.3396 - accuracy: 0.8388 - val_loss: 0.1977 - val_accuracy: 0.9178
Epoch 2/10
192/192 [==============================] - 14s 75ms/step - loss: 0.1444 - accuracy: 0.9445 - val_loss: 0.2052 - val_accuracy: 0.9130
Epoch 3/10
192/192 [==============================] - 11s 57ms/step - loss: 0.0979 - accuracy: 0.9639 - val_loss: 0.2380 - val_accuracy: 0.9205
Epoch 4/10
192/192 [==============================] - 12s 60ms/step - loss: 0.0720 - accuracy: 0.9751 - val_loss: 0.2465 - val_accuracy: 0.9165
Epoch 5/10
192/192 [==============================] - 13s 67ms/step - loss: 0.0500 - accuracy: 0.9831 - val_loss: 0.2746 - val_accuracy: 0.9175
Epoch 6/10
192/192 [==============================] - 13s 67ms/step - loss: 0.0311 - accuracy: 0.9903 - val_loss: 0.3516 - val_accuracy: 0.9137
Epoch 7/10
192/192 [==============================] - 14s 74ms/step - loss: 0.0167 - accuracy: 0.9952 - val_loss: 0.4303 - val_accuracy:

### Adding Dropout

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [49]:
y_pred=model.predict(X_test)

189/189 [==============================] - 3s 11ms/step


In [50]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [51]:
from sklearn.metrics import confusion_matrix

In [52]:
confusion_matrix(y_test,y_pred)

array([[3119,  300],
       [ 235, 2381]])

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9113504556752279

In [54]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      3419
           1       0.89      0.91      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035



# Testing model on Test data

In [76]:
test = pd.read_csv('test.csv')
true_test = pd.read_csv('submit.csv')

In [78]:
test['label'] = true_test['label']

In [79]:
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  \
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...   
1                      NaN  Russian warships ready to strike terrorists ne...   
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...   
3            Daniel Victor  If at first you don’t succeed, try a different...   
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...   

   label  
0      0  
1      1  
2      0  
3      1  
4      1

In [80]:
test.isnull().sum()

id          0
title     122
author    503
text        7
label       0
dtype: int64

In [81]:
test.dropna(inplace=True)

In [82]:
test.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [83]:
#Preprocessing

news_test=test.copy()
news_test.reset_index(inplace=True)

In [84]:
corpus_test = []
for i in range(0, len(news_test)):
    review = re.sub('[^a-zA-Z]', ' ', news_test['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus_test.append(review)


In [85]:
corpus_test

['specter trump loosen tongu purs string silicon valley new york time',
 'nodapl nativ american leader vow stay winter file lawsuit polic',
 'tim tebow attempt anoth comeback time basebal new york time',
 'keiser report meme war e',
 'pelosi call fbi investig find russian donald trump breitbart',
 'weekli featur profil randi shannon',
 'u gener admir endors trump command chief',
 'work class hero john brennon',
 'rise mandatori vaccin mean end medic freedom',
 'communist terror small busi',
 'comput programm come forward admit paid rig vote booth trump right usa newsflash',
 'thiev take chunk chang pound berlin museum new york time',
 'new england patriot owner still sore n f l payback sight new york time',
 'colleg republican yaf sue berkeley ann coulter event breitbart',
 'trump melt accus us postal servic steal elect clinton',
 'visit madagascar leav red swimsuit lemur recip home new york time',
 'rees peanut butter cup cheap full toxic chemic',
 'presid obama presid elect donald tr

In [86]:
#one hot encoding on test
onehot_repr_test=[one_hot(words,voc_size)for words in corpus_test]
onehot_repr_test

[[1588, 5866, 183, 2751, 2532, 983, 3111, 4313, 1070, 3629, 1069],
 [5639, 4060, 2074, 3969, 1611, 1182, 5953, 3402, 3021, 4924],
 [4700, 483, 1298, 5924, 4052, 1069, 4364, 1070, 3629, 1069],
 [3363, 4820, 3567, 4911, 2873],
 [903, 1855, 3839, 2261, 1656, 2038, 2225, 5866, 2210],
 [3920, 439, 3415, 5562, 2539],
 [3942, 709, 5089, 3987, 5866, 2564, 3786],
 [4366, 2911, 5187, 68, 3534],
 [2671, 3311, 1639, 583, 3371, 4453, 4698],
 [1523, 5284, 2802, 2919],
 [4675, 4012, 2334, 439, 1578, 3617, 351, 5129, 2028, 5866, 4875, 696, 3589],
 [1334, 1865, 5373, 5306, 3430, 1232, 3859, 1070, 3629, 1069],
 [1070,
  304,
  5232,
  1154,
  4396,
  428,
  1393,
  5448,
  4519,
  2037,
  242,
  1070,
  3629,
  1069],
 [4608, 3280, 786, 85, 5131, 2604, 1613, 1076, 2210],
 [5866, 3461, 5267, 4110, 5263, 5010, 999, 4149, 937],
 [4658, 4166, 1833, 80, 652, 2786, 5964, 1523, 1070, 3629, 1069],
 [3280, 4198, 4508, 3825, 5111, 954, 2541, 4764],
 [319, 2252, 319, 4149, 2225, 5866, 5793, 3098, 4765],
 [1528, 18

In [87]:
#sequencing
embedded_docs_test=pad_sequences(onehot_repr_test,padding='pre',maxlen=sent_length)

In [88]:
embedded_docs_test

array([[   0,    0,    0, ..., 1070, 3629, 1069],
       [   0,    0,    0, ..., 3402, 3021, 4924],
       [   0,    0,    0, ..., 1070, 3629, 1069],
       ...,
       [   0,    0,    0, ..., 1070, 3629, 1069],
       [   0,    0,    0, ..., 1070, 3629, 1069],
       [   0,    0,    0, ..., 1070, 3629, 1069]], dtype=int32)

In [89]:
#testing model

y_pred_test=model.predict(embedded_docs_test)

143/143 [==============================] - 2s 11ms/step


In [90]:
y_pred_test=np.where(y_pred_test > 0.6, 1,0)

In [91]:
from sklearn.metrics import confusion_matrix

confusion_matrix(test['label'],y_pred_test)


array([[1550,  663],
       [1040, 1322]])

In [92]:
from sklearn.metrics import accuracy_score
accuracy_score(test['label'],y_pred_test)

0.62775956284153

In [94]:
print(classification_report(test['label'],y_pred_test))

              precision    recall  f1-score   support

           0       0.60      0.70      0.65      2213
           1       0.67      0.56      0.61      2362

    accuracy                           0.63      4575
   macro avg       0.63      0.63      0.63      4575
weighted avg       0.63      0.63      0.63      4575

